export const AVAILABILITY_CREATE_REQUEST = 'AVAILABILITY_CREATE_REQUEST'
export const AVAILABILITY_CREATE_SUCCESS = 'AVAILABILITY_CREATE_SUCCESS'
export const AVAILABILITY_CREATE_FAIL = 'AVAILABILITY_CREATE_FAIL'


export const AVAILABILITY_DELETE_REQUEST = 'AVAILABILITY_DELETE_REQUEST'
export const AVAILABILITY_DELETE_SUCCESS = 'AVAILABILITY_DELETE_SUCCESS'
export const AVAILABILITY_DELETE_FAIL = 'AVAILABILITY_DELETE_FAIL'