export const RESERVATION_CREATE_REQUEST = 'RESERVATION_CREATE_REQUEST'
export const RESERVATION_CREATE_SUCCESS = 'RESERVATION_CREATE_SUCCESS'
export const RESERVATION_CREATE_FAIL = 'RESERVATION_CREATE_FAIL'


export const RESERVATION_DELETE_REQUEST = 'RESERVATION_DELETE_REQUEST'
export const RESERVATION_DELETE_SUCCESS = 'RESERVATION_DELETE_SUCCESS'
export const RESERVATION_DELETE_FAIL = 'RESERVATION_DELETE_FAIL'